name: CD - Deploy to DeWeb

on:
  push:
    branches: [dev, main]

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - id: set-matrix
        run: |
          matrix=$(jq --arg branchName "${{ github.ref_name }}" 'map(
            . | select(.branch == $branchName)
          )' <<< '[
            {
              "branch": "dev",
              "network": "buildnet",
              "config_file": "deweb_cli_config.buildnet.json"
            },
            {
              "branch": "main",
              "network": "mainnet",
              "config_file": "deweb_cli_config.mainnet.json"
            }
          ]')
          echo "matrix={\"include\":$(echo $matrix)}" >> $GITHUB_OUTPUT

  deploy:
    needs: matrix_prep
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Get commit hash
        id: vars
        run: echo "commit_hash=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT

      - name: Build
        env:
          VITE_GOSSIP_API_URL: ${{ vars.GOSSIP_API_URL }}
          VITE_INVITE_DOMAIN: ${{ matrix.branch == 'dev' && vars.INVITE_DOMAIN_DEV || vars.INVITE_DOMAIN_MAIN }}
          VITE_APP_BUILD_ID: ${{ steps.vars.outputs.commit_hash }}
        run: npm run build

      - name: Deploy ${{ matrix.branch }} → ${{ matrix.network }}
        id: deploy
        uses: massalabs/deweb-gh-action@v0.1.0
        with:
          config_file: ./${{ matrix.config_file }}
          source_folder: ./dist
        env:
          MASSA_DEWEB_SECRET_KEY: ${{ matrix.network == 'buildnet' && secrets.PRIVATE_KEY || secrets.MASSA_DEWEB_MAINNET_PKEY }}

      - name: URL
        run: echo "${{ matrix.branch }} deployed → ${{ steps.deploy.outputs.deployed-website }}"
